# Build stage
FROM node:20 AS build

WORKDIR .

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Serve stage
FROM node:20-alpine

WORKDIR .
RUN npm install -g serve

COPY --from=build ./dist ./dist

EXPOSE 8000

CMD ["serve", "-s", "dist", "-l", "8000"]